"""
Visual timetable — generates a colored HTML grid and opens it in the browser.
Rows = time slots, columns = venues, one colored card per exam.
Colors follow the student groups so clashes would be visually obvious.

Run standalone:  python viz.py
Or from the CLI: option 6.
"""

import webbrowser
import os
import time

from engine import (load_data, solve, verify, attendance, quality_score)
from dataio import pretty_date, period_text

PALETTE = ["#4e79a7", "#f28e2b", "#59a14f", "#e15759",
           "#76b7b2", "#af7aa1", "#edc948", "#9c755f"]


def group_colors(data):
    return {g: PALETTE[i % len(PALETTE)] for i, g in enumerate(sorted(data["groups"]))}


def build_html(assignment, data):
    colors = group_colors(data)
    quality = quality_score(assignment, data)
    clashes = len(verify(assignment, data))
    title = data.get("title", "TIMETABLE")

    by_cell = {}
    for name, (slot, venue) in assignment.items():
        by_cell[(slot, venue)] = name

    # show only venues that actually host something (keeps the grid readable
    # when the dataset lists the college's full room inventory)
    used = {venue for _slot, venue in assignment.values()}
    shown_venues = [v for v in data["venues"] if v["name"] in used]

    head = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{title}</title>
<style>
  body {{ font-family: Segoe UI, Arial, sans-serif; margin: 24px; background:#f7f7f9; }}
  h1 {{ font-size: 22px; margin-bottom: 4px; }}
  .period {{ color:#666; font-size:14px; margin-bottom:10px; }}
  .meta {{ color:#444; margin-bottom:16px; }}
  .badge {{ display:inline-block; padding:3px 10px; border-radius:12px;
           color:white; font-size:13px; margin-right:8px;
           background:{'#59a14f' if clashes == 0 else '#e15759'}; }}
  table {{ border-collapse: collapse; width:100%; }}
  th, td {{ border:1px solid #ddd; padding:6px; vertical-align:top; }}
  th {{ background:#2f3542; color:white; font-size:13px; }}
  td.slot {{ background:#2f3542; color:white; font-weight:bold;
             white-space:nowrap; width:110px; }}
  td.slot .sd {{ font-weight:normal; font-size:10.5px; color:#a9b0c4;
                 margin-top:2px; }}
  .card {{ border-radius:6px; padding:6px 8px; color:white; font-size:12.5px; }}
  .card b {{ font-size:13px; }}
  .legend span {{ display:inline-block; padding:2px 10px; border-radius:10px;
                  color:white; font-size:12px; margin:2px; }}
  .empty {{ background:#fafafa; }}
</style></head><body>
<h1>{title}</h1>
{f'<div class="period">{period_text(data)}</div>' if period_text(data) else ''}
<div class="meta">
  <span class="badge">{clashes} clashes</span>
  Quality score: <b>{quality}/100</b> &nbsp;|&nbsp;
  Generated by CSP engine (backtracking + MRV + soft constraints)
</div>"""

    legend = '<div class="legend">Groups: ' + "".join(
        f'<span style="background:{c}">{g} ({data["groups"][g]})</span>'
        for g, c in colors.items()) + "</div><br>"

    rows = ["<table><tr><th></th>" +
            "".join(f"<th>{v['name']}<br><small>cap {v['capacity']}</small></th>"
                    for v in shown_venues) + "</tr>"]

    dates = data.get("slot_dates") or {}
    for slot in data["slots"]:
        if slot in dates:
            cells = [f'<td class="slot">{slot}'
                     f'<div class="sd">{pretty_date(dates[slot])}</div></td>']
        else:
            cells = [f'<td class="slot">{slot}</td>']
        for v in shown_venues:
            name = by_cell.get((slot, v["name"]))
            if not name:
                cells.append('<td class="empty"></td>')
                continue
            task = data["_by_name"][name]
            color = colors[task["groups"][0]]
            groups = ", ".join(task["groups"])
            cells.append(
                f'<td><div class="card" style="background:{color}">'
                f'<b>{name}</b><br>{groups}<br>'
                f'{attendance(task, data)} students &middot; {task["staff"]}'
                f"</div></td>")
        rows.append("<tr>" + "".join(cells) + "</tr>")
    rows.append("</table>")

    footer = (f"<p style='color:#666;font-size:12px'>Generated "
              f"{time.strftime('%Y-%m-%d %H:%M')} &middot; "
              f"ST5001CMD coursework — exam-timetable-scheduler</p>")

    return head + legend + "".join(rows) + footer + "</body></html>"


def show(assignment, data, filename="timetable.html", open_browser=True):
    html = build_html(assignment, data)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"Visual timetable written to {filename}")
    if open_browser:
        webbrowser.open("file://" + os.path.abspath(filename))


if __name__ == "__main__":
    data = load_data("data/softwarica_exams.json")
    data["_by_name"] = {t["name"]: t for t in data["tasks"]}
    result = solve({}, data["tasks"], data, {"attempts": 0, "backtracks": 0})
    if result is None:
        print("No valid timetable to draw.")
    else:
        show(result, data)
